Merge changes from release/csm-1.2 into master.
Cray-HPE/cfs-operator pull request #38
Opened 2022-03-02 22:32 UTC by dlaine-hpe

## Summary and Scope

Take the collected changes from release/csm-1.2 that have not been merged to master and get them moved over.

## Testing
### Test description:

Not tested - just merging already tested changes.

## Risks and Mitigations

Low risk - this will be completely tested in powerDNS transition work.

## Pull Request Checklist

- [X] Version number(s) incremented, if applicable
- [X] Copyrights updated
- [X] License file intact
- [X] Target branch correct

2022-03-02 22:37 UTC, jsl-hpe approved these changes

2022-03-02 22:38 UTC, rkleinman-hpe commented
License check failures: https://github.com/Cray-HPE/.github/runs/5399283388?check_suite_focus=true

2022-03-02 22:38 UTC, rkleinman-hpe requested changes
https://github.com/Cray-HPE/.github/runs/5399283388?check_suite_focus=true

2022-03-02 23:16 UTC, rbak-hpe approved these changes

2022-03-04 14:51 UTC, rkleinman-hpe approved these changes

2022-03-04 15:11 UTC, merged